services:
  todo-app:
    build: ./
    command: ./wait-for-postgres.sh db ./todo-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=POSTGRES_PASSWORD

  db:
    container_name: todo_db
    image: postgres:13
    platform: linux/x86_64
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
